### ISSUE TITLE
Notify the user, if a role has no corresponding path in .ServerMaps

### ISSUE THREAD

**Issue by AkosLukacs** [chucknorris/dropkick#32]
dropkick just silently fails, if a given Role has no corresponding entry in the current ServerMaps file. Maybe throw an exception, but show something.
## Example:

I have a test Role: `public static Role Test1 { get; set; }`, but no entry named "Test1" in ServerMaps.
Command line parameters:

>    dk.exe execute /deployment:D1.dll /settings:....\settings /roles:Test1

And the result (notice the typo "Tes**z**t1"):

> ---
> 
> DropkicK v0.4.13.0
> ---
> 
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Command:     Execute
> Environment: LOCAL
> Role:        Test1
> 
> Server Maps:   '....\settings\LOCAL.servermaps' - Looks Good!
> 
> Settings Path: '....\settings\LOCAL.js' - Looks Good!
> Looking for deployment dll 'D1.dll' at 'xxx\D1.dll'
> Deployment Method: 'Specific Assembly Specified'
> Deployment Found:  'D1'
> 
> Server Mappings
>   'Teszt1'
>     'localhost'
> 
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please review the settings above and when you are ready,
>   Press 'ctrl+c' to cancel.
>   Press enter to kick it out there

No error message, just back to console.
I know this is just RTFM, but confusing at a minimum. And not exactly evident, that something is missing, and pretty hard to figure out what just happened, if you don't know where to look.

**Comment by ferventcoder** [comment]
That's probably not a bad idea to throw an error.

**Comment by ferventcoder** [comment]
Unless you can think of a case where you would just want it to move on and execute even if a role wasn't found. I can't really think of one off of the top of my head though.
