### ISSUE TITLE
Enhancement: Silent switch

### ISSUE THREAD

**Issue by ferventcoder** [chucknorris/dropkick#4]
I need to be able to run with a silent switch.

**Comment by Gaikotsu2** [comment]
k, did you run this by dru? by and large it's still his project...

Matthew Brubaker
MatthewSBrubaker@gmail.com
(785) 215-7061

On Thu, May 19, 2011 at 5:23 PM, ferventcoder
reply@reply.github.com
wrote:

**Comment by ferventcoder** [comment]
yep.

**Comment by Gaikotsu2** [comment]
alright, i will get to it when i have some time.

Matthew Brubaker
MatthewSBrubaker@gmail.com
(785) 215-7061

On Fri, May 20, 2011 at 9:08 AM, ferventcoder
reply@reply.github.com
wrote:

**Comment by ferventcoder** [comment]
Most of this is done already. I'm just logging the work I am putting into
it.

---

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder
On May 22, 2011 3:25 PM, "Kaithos" <
reply@reply.github.com>
wrote:

**Comment by seif** [comment]
https://github.com/markransome/dropkick/commit/35b3e4080206259a3e73d9934397ca828ab1ab70 
Mark had tried the Silent switch, but it just didn't work, as I recall he said it was a problem with how the parser read /S\* changing it to /Quiet got it working! :)

**Comment by ferventcoder** [comment]
Damn, you guys have a lot of work going into dropkick. Thought about pull requesting some of that?

**Comment by ferventcoder** [comment]
When you guys get a chance, start structuring your tests in this format...

**Comment by ferventcoder** [comment]
https://github.com/chucknorris/dropkick/blob/master/product/dropkick.tests/Engine/DeploymentCommandLineParserSpecs.cs

**Comment by ferventcoder** [comment]
For any tasks that you add that is. I was thinking it was an issue with /s\* - but also an issue that I was trying to run as a switch and not a definition.

**Comment by seif** [comment]
Like the spec structure. I don't work with the chaps any more, but I'll nudge @markransome to let them know, as they are using dk, and will probably do some changes.

We are not using dk at the new job yet ;) so I won't be issuing many pull requests in the near future, I'll add some specs for the NServiceBus task and do a pull request when I get a change.

Thanks for all your work!

**Comment by ferventcoder** [comment]
Switches are defined by -- instead of /. Talked to Dru about this and it's what the monadic command line parser expects.

**Comment by ferventcoder** [comment]
It's due in part to https://github.com/drusellers/Magnum/blob/master/src/Magnum/CommandLineParser/TextCommandLineParser.cs#L70 . If you have one letter afterwards, as in '/s' it will work, but anymore letters it believes it is a definition.

So for a switch/flag it is '- -' (minus the space), '-s', and '/s' - but one letter with the others. The one we are looking for with this one will be the full '--silent'

**Comment by ferventcoder** [comment]
This is fixed in 86752ef
