### ISSUE TITLE
Access currently executing role

### ISSUE THREAD

**Issue by danielmarbach** [chucknorris/dropkick#51]
Hy

I have scenarios where configuration files are not only environment specific but also role specific. For example I have different RavenDb servers in place. For each ravendb server I have a configuration file for the ravendb instance. Practically I want to do the following:

```
        server.CopyFile(@".\configs\{{Environment}}.{{ExecutingRole}}.Raven.Server.exe.config")
            .ToDirectory(installDirectory).RenameTo(@"Raven.Server.exe.config");
```

I see from the code it would be possible by adding an ExecutingRole to the settings and then add the following;

```
    protected void DeploymentStepsFor(Role inputRole, Action<ProtoServer> action)
    {
        var role = ServerRole.GetRole(inputRole);
        Settings.Role = role.Name;
        role.BindAction(action);
    }
```

Attention: Quick hack.

Do you think that makes sense?

Daniel

**Comment by drusellers** [comment]
out of curiosity what is the use case??

-d

**Comment by danielmarbach** [comment]
As described above we have different environments:

local (development)
Test (test environment)
Prod (production env.)

Now lets say we have the following roles:

Web
Webdb
Backend
BackendDb

Both webdb and backend db have ravendb in place. For example webdb should have some analyzers running and be installed on port 8801.backenddb should run on 8880 and have also specific settings. With the current approach I have to use own naming convention for the config files and hardcode these. Normally I would like to have configs like:

Prod.Webdb.raven.server.config
Prod.backenddb.ravenserver.config

This would also allow me to build role specific folders kn the harddrive. Clear?

Daniel

**Comment by drusellers** [comment]
So on a box that hosts everything, all of these config files go into the same spot. right? therefore you need to be able to have each one use a different name.

**Comment by drusellers** [comment]
{{Role}}

**Comment by danielmarbach** [comment]
Thanks. Any plans for next release?

**Comment by drusellers** [comment]
not yet. do you need a nuget or can you run from source?

-d

On Wed, Jul 18, 2012 at 1:47 AM, danielmarbach <
reply@reply.github.com

**Comment by danielmarbach** [comment]
I run now form locally built nuget.

-----Original Message-----
