### ISSUE TITLE
Project is dead?

### ISSUE THREAD

**Issue by kiquenet** [chucknorris/dropkick#60]
The project continues development or dead?

Anyways, why not working together?
https://github.com/chucknorris/dropkick
https://github.com/mmooney/Sriracha.Deploy
https://github.com/asimov-deploy/asimov-deploy-winagent
https://wolfpack.codeplex.com/

Thanks a lot.

**Comment by ferventcoder** [comment]
Not dead, just needs a set of maintainers who are actively using.
