### ISSUE TITLE
Question: Assembly.LoadFrom in finder

### ISSUE THREAD

**Issue by mmooney** [chucknorris/dropkick#61]
Hi guys,

Not sure if this is the right place to ask questions, but I ran into a problem with the deployment finder, and wanted to run a possible fix by you.

So this line is the problem:
https://github.com/chucknorris/dropkick/blob/master/product/dropkick/Engine/DeploymentFinders/AssemblyWasSpecifiedAssumingOnlyOneDeploymentClass.cs#L45

In that line, once it have the path to DLL that contains the deployment code, it calls Assembly.LoadFile to load it.  The problem I ran into is that this DLL references a few more DLLs, which are colocated with the deployment DLL, and LoadFile will not load those dependencies automatically.  It will assume that all dependencies are in the current executing directory (where ever dk.exe is located) which does not have the dependencies.  For a cutting edge explanation, here is an 11 year old blog post: http://blogs.msdn.com/b/suzcook/archive/2003/09/19/loadfile-vs-loadfrom.aspx

This a key difference between LoadFrom and LoadFile.  LoadFrom will load the dependencies colocated with the deployment DLL, but LoadFile will not.  

In my case, i'm using a copy of dk.exe sitting in a single directory, and then using that to execute a bunch of deployments from other directories, so it's not practical to put all of the dependency DLLs in the same directory as dk.exe.  

Obviously in my case it's easier to change LoadFile to LoadFrom so that the dependencies will automatically get loaded.  However, I wasn't sure if LoadFile was used intentionally because the deployemtn DLL in turn is also going to reference dropkick.dll, and you wanted to make sure that the correct dk.exe dll version was used.  However if they actually was a breaking mismatch in the dropkick.dll versions, I'm guessing that it burst into flames with some gory error messages anyway, elegantly telling the user that they have a problem.

Anywho, any issue if I submit a PR changing that to LoadFrom?  

I'll probably have another one coming after that to be able to specify a specific deployment object to use if multiple objects exist in a DLL.  Right now it seems like it only allows one per DLL,and I'm going to be building a whole bunch of a deployment automation tool (https://github.com/mmooney/Sriracha.Deploy), and it would be a lot easier to be able to put them all in the same DLL.

Thanks

**Comment by ferventcoder** [comment]
Chucknorrisframework at google groups dot com is always a good place to ask questions. :)

**Comment by ferventcoder** [comment]
Interesting. Submit a PR for the LoadFrom. I think we went one way for perf.

**Comment by mmooney** [comment]
Done!
