### ISSUE TITLE
Enhancement: Clear ACLs from a folder

### ISSUE THREAD

**Issue by ferventcoder** [chucknorris/dropkick#8]
Some of the work was done here, but it needs to be finished out.

**Comment by ferventcoder** [comment]
Fixed in 0.3.11 (d38058d).

Gist: https://gist.github.com/1005305

**Comment by ferventcoder** [comment]
``` csharp
p.Clear()
     .Preserve(settings.UserGroupA, settings.UserGroupB)
     .Preserve(WindowsIdentity.GetCurrent().Name)
     .RemoveAdministratorsGroup()
     .RemoveSystemAccount()
     .RemoveUsersGroup();
```

**Comment by Gaikotsu2** [comment]
Both # 8 and #9 i believe are done, i just need to push it to my
github and issue the pull request.

Matthew Brubaker
MatthewSBrubaker@gmail.com
(785) 215-7061

On Sat, Jun 4, 2011 at 8:21 AM, ferventcoder
reply@reply.github.com
wrote:

**Comment by Gaikotsu2** [comment]
err...#7 and #8, the ones regarding ACL permissions.

Matthew Brubaker
MatthewSBrubaker@gmail.com
(785) 215-7061

**Comment by ferventcoder** [comment]
These were completed already. I had to remove the fhlb accounts from the default preserved since it doesn't apply to everyone else, but I finished the clear config with a preserve option so they can be added back in.

**Comment by Gaikotsu2** [comment]
i saw that, it seems there were a number of changes made since the last time i pulled from chuck...i'll have to get up to current tomorrow

**Comment by ferventcoder** [comment]
The logging has really been cleaned up in the latest version (I just pushed a few minutes ago) - https://github.com/chucknorris/dropkick/commit/b43d82d2aaf6c659a82a53dae39a8a42b6cf5ca2
